services:
  api_node-1: &api_config
    image: bretfisher/httpenv
    networks:
      internal_net:
        aliases: 
          - lb-search
    restart: unless-stopped

  api_node-2:
    <<: *api_config

  api_node-3:
    <<: *api_config

  network-tester:
    image: rockylinux/rockylinux:10
    networks:
      internal_net:
    command: sleep infinity

networks: 
  internal_net:
    driver: bridge