services:
  api_node-1: &api_config
    image: bretfisher/httpenv
    networks:
      internal_net:
        aliases: 
          - lb-search
    restart: unless-stopped

  api_node-2:
    <<: *api_config

  api_node-3:
    <<: *api_config

  network-tester:
    build:
      context: .
      dockerfile: tester.Dockerfile
    networks:
      internal_net:
    command: sleep infinity

networks: 
  internal_net:
    driver: bridge